### ISSUE TITLE
Addon currently does not work - many errors on login

### ISSUE THREAD

**Issue by Rezy942** [GurliGebis/WoWAddon-BattlePetCompletionist#1]
Hello,

Getting a bunch of errors on login (with all addons disabled and enabled). Addon does not function in any way because of this.
Here are the errors I get separated by ---------------------- :

3x ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@AllTheThings/lib/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@BattlePetCompletionist/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

--------------------------------------------------------------------------------------------------------------------------------

3x ...ttlePetCompletionist/Modules/Config/ConfigModule.lua:23: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@AllTheThings/lib/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@BattlePetCompletionist/Modules/Config/ConfigModule.lua"]:23: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceConfigDialog-3.0"."

--------------------------------------------------------------------------------------------------------------------------------

3x ...lePetCompletionist/Modules/Minimap/MinimapModule.lua:26: attempt to index field 'AceDB' (a nil value)
[string "@BattlePetCompletionist/Modules/Minimap/MinimapModule.lua"]:26: in function <...lePetCompletionist/Modules/Minimap/MinimapModule.lua:25>
[string "=[C]"]: ?
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 UpdateMinimap = <function> defined @BattlePetCompletionist/Modules/Minimap/MinimapModule.lua:49
 Enable = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 CreateMinimapIcon = <function> defined @BattlePetCompletionist/Modules/Minimap/MinimapModule.lua:57
 defaultModuleLibraries = <table> {
 }
 baseName = "BattlePetCompletionist"
 SetEnabledState = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 SetDefaultModulePrototype = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 enabledState = true
 ShowIcon = <function> defined @BattlePetCompletionist/Modules/Minimap/MinimapModule.lua:33
 OnInitialize = <function> defined @BattlePetCompletionist/Modules/Minimap/MinimapModule.lua:25
 moduleName = "MinimapModule"
 GetName = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "BattlePetCompletionist_MinimapModule"
 HideIcon = <function> defined @BattlePetCompletionist/Modules/Minimap/MinimapModule.lua:41
 IsEnabled = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 DisableModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'AceDB' (a nil value)"

--------------------------------------------------------------------------------------------------------------------------------

2x ...s/BattlePetCompletionist/Modules/Data/DataModule.lua:29: attempt to index field 'AceDB' (a nil value)
[string "@BattlePetCompletionist/Modules/Data/DataModule.lua"]:29: in function `ShouldPetBeShown'
[string "@BattlePetCompletionist/Modules/Map/MapModule.lua"]:59: in function `LoadMapData'
[string "@BattlePetCompletionist/Modules/Map/MapModule.lua"]:39: in function `RefreshAllData'
[string "@BattlePetCompletionist/Modules/Map/MapModule.lua"]:162: in function `UpdateWorldMap'
[string "@BattlePetCompletionist/Modules/Map/MapModule.lua"]:168: in function <...Ons/BattlePetCompletionist/Modules/Map/MapModule.lua:165>
[string "=[C]"]: ?
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:754: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 baseName = "BattlePetCompletionist"
 PetData = <table> {
 }
 SetEnabledState = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetOwnedPets = <function> defined @BattlePetCompletionist/Modules/Data/DataModule.lua:59
 enabledState = true
 SetDefaultModuleState = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 GetPetsInMap = <function> defined @BattlePetCompletionist/Modules/Data/DataModule.lua:24
 moduleName = "DataModule"
 GetName = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "BattlePetCompletionist_DataModule"
 SetDefaultModulePrototype = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 ShouldPetBeShown = <function> defined @BattlePetCompletionist/Modules/Data/DataModule.lua:28
 DisableModule = <function> defined @BattlePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
speciesId = 3328
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'AceDB' (a nil value)"

--------------------------------------------------------------------------------------------------------------------------------

3x BattlePetCompletionist/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1 (null)

--------------------------------------------------------------------------------------------------------------------------------

3x BattlePetCompletionist/Modules/Config/ConfigModule.lua:1 (null)

--------------------------------------------------------------------------------------------------------------------------------

3x Interface\FrameXML\Bindings.xml:1 BattlePetCompletionist/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)

--------------------------------------------------------------------------------------------------------------------------------

3x Interface\FrameXML\Bindings.xml:1 BattlePetCompletionist/Modules/Config/ConfigModule.lua:1 (null)

**Comment by GurliGebis** [comment]
Ahh, I see.
I think I know what the issue is, and I'll post an updated version later tonight 🙂

**Comment by GurliGebis** [comment]
@Rezy942 I have just pushed 10.1.0-20230613_2 which fixes the issue.
The problem was that other addons on my machine had the missing Ace3 libraries loaded, so it worked fine for that.
With the changes here, it works on my machine with only this addon loaded.

**Comment by GurliGebis** [comment]
It might take a while for Curseforge to approve the file and push it across their CDN, but it should be available soon(ish) 🙂

**Comment by Rezy942** [comment]
Tested the addon just now - works flawlessly with my 100+ addons. Will open a ticket if I find any bugs! Take care and ty again

**Comment by GurliGebis** [comment]
Sounds great 🙂
Pushed a new release a little earlier tonight, which has support for filtering the pet sources
