### ISSUE TITLE
Broker integration

### ISSUE THREAD

**Issue by Mike160770** [GurliGebis/WoWAddon-BattlePetCompletionist#11]
Nice work - what I would suggest: integration in a broker (e.g. bazooka), where you could see how many pets from the zone you are in have been collected (like 7/10).

**Comment by Mike160770** [comment]
Yeah - PetTracker Broker e.g.
(has to be installed together with PetTracker).

**Comment by GurliGebis** [comment]
Okay, I'll see what I can do.
I don't have a timeframe right now though, but hopefully soon 🙂

**Comment by Mike160770** [comment]
No problem - take your time and thx for your efforts.

**Comment by davidmc24** [comment]
I've got a version of this I'm working on

**Comment by GurliGebis** [comment]
@davidmc24 I really appriciate that 😃
Thank you.

I got started on it, but haven't got around to finish it, so do feel free to work on it - what I have is badly broken right now, so not a great starting point I would say 🙂

**Comment by GurliGebis** [comment]
This has been fixed in `10.2.6-20240418-1`
