### ISSUE TITLE
Feature Request: Tooltip Shows Collected Breed(s)

### ISSUE THREAD

**Issue by Llamagirl** [GurliGebis/WoWAddon-BattlePetCompletionist#12]
I installed this after seeing comments on the LUA errors issue with PetTracker. The three things I really liked PetTracker for (and truly the only reason I had it installed) was:
1. The tooltip showed the breed(s) I had already collected so I could mouseover and see if I wanted to bother with that pet (again).
2. PetTracker showed the list of pets I had collected and not collected from the current area. It helped me change focus from whatever I was doing in the region to finding that last pet or two that I needed. You already have someone mentioning adding a broker so there would be the ability to see 7/10 pets collected. That would suffice as well (although a list like PetTracker is pretty handy.)
3. Seeing the spells the other pet had during the battle. I see your comments to look at the other addon for anything pet-battle UI related. I'll take a look at that. Thanks for the tip.

I need to check out your other features in this addon. I don't think I use all the features you've released. Thanks!

**Comment by GurliGebis** [comment]
I will see what I can do.
Since I cannot use the code from PetTracker (due to licensing restrictions), I cannot promise anything.

**Comment by GurliGebis** [comment]
Broker support has been added to the latest release
