### ISSUE TITLE
Feature Request: Option to auto-forfeit vs teams with no upgrades, with rarity threshold 

### ISSUE THREAD

**Issue by MystbornGames** [GurliGebis/WoWAddon-BattlePetCompletionist#13]
Hello! Very much appreciate the work you've put in to replace PetTracker. 

I would like to request a feature that functions like Pet Tracker's auto forfeit — if there are no upgrades available in a battle, a prompt comes up to forfeit the fight. 

It would be super handy to have something like that and be able to select a rarity threshold, so the forfeit prompt comes up for anything below Uncommon or Rare, even if you don't have the pet already. (I don't bother catching anything if it's below rare unless it's a difficult pet to find — I'm sure many others are the same.)

I understand you want people to use Pokemon Trainer NG, but I already have a myriad of pet battle mods installed (Battle Pet Completionist, Battle Pet BreedID, BattlePetCount NG, Pet Battle Scripts, and Rematch) and would prefer to not have to install yet another one that provides the same functions as those, and again I'm sure I'm not the only one. A forfeit option makes sense for a completionist addon because it's collector-oriented rather than exclusively battle.

Thank you

**Comment by GurliGebis** [comment]
I will take a look at it, and see what I can do 🙂

**Comment by ZForceSeattle** [comment]
Can I second the request above!!!! It would be awesome to have an auto-forfeit. If I'm going after a pet I don't have, and I kill it, I don't bother staying in the match. It's a waste of time, especially if I have the rest. It could be a conditional set of check marks. 

If I have the other pets, forfeit the match? 
If the additional pets are higher quality than what I have, stay in the match.
Could you show me which pets are the best of the fighting group? Which one should I be fighting towards?

I didn't realize how nice these features would be until I got to this 10.2 patch.  With the Battle Pets being so crucial for additional pets, some help with these decisions would be excellent.  It's already having a hard time when I'm at the auction. I have to go to the Xufu battle pet site every time I look for pets and their worth. To see if quality, etc...

**Comment by GurliGebis** [comment]
That would require quiet a bit of a change, and I don't have the needed info for it anyway (like what defines if a pet is better than another pet? maybe a P/P is worse than an B/B for specific pets).
Regarding notifying if the pet you want to capture is dead, I'll keep that in mind for later on, but it isn't something that I'll include in the first implementation of this 🙂

**Comment by GurliGebis** [comment]
Implemented in 10.2.0-20231225_1, which I have just released.
@ZForceSeattle I'll keep your idea about notifying if the pet you want to capture dies in the back of my head for later.

**Comment by GurliGebis** [comment]
![billede](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/13592619/ac5d0d5e-a360-48e8-8a3c-07e0b2f487a8)
