### ISSUE TITLE
FEATURE REQUEST: Placement of Pins

### ISSUE THREAD

**Issue by ZForceSeattle** [GurliGebis/WoWAddon-BattlePetCompletionist#14]
Can we please have the options like it is in Gathermate on the spacing, showing, and distance of pets? It shows fewer in those areas. I've used my slower hover disk, and they are not there. As you can see in the picture, the pictures prevent me from seeing other things. I want the option to place maybe fewer or fade them some—much the way Gathermate does it. It wasn't fun before I started catching pets over here because I could not find the quest markers. It's a little better now, but it still causes problems. 

Thank you! 

![image](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/59213553/ae73f230-3d7c-49e0-acec-7ec7b6f316bf)

![image](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/59213553/b046394c-8723-474b-809a-a6dd557ab923)

As you can see in the second picture, I have "small" pins selected.

**Comment by GurliGebis** [comment]
Do you happen to have a screenshot on how it looks with Gathermate?
