### ISSUE TITLE
Feature Request: Filter Pets on Map

### ISSUE THREAD

**Issue by nickdwaters** [GurliGebis/WoWAddon-BattlePetCompletionist#16]
I love your add-on.

A situation arises where you may want to get multiple of just one type of pet that is widely distributed across several zones, such as the Unborn Val'kyr. Or if you want a certain pet, just see that one in general.

Could you add a way to accomplish that?

Thank you very much

**Comment by GurliGebis** [comment]
Would a text box in the settings dialog, where you can enter part of the pet name, and the if the name contains what you wrote, it will be shown?

**Comment by nickdwaters** [comment]
Yes that’d be perfect :)On Feb 23, 2024, at 3:27 AM, GurliGebis ***@***.***> wrote:﻿
Would a text box in the settings dialog, where you can enter part of the pet name, and the if the name contains what you wrote, it will be shown?

**Comment by GurliGebis** [comment]
I will see what I can do, once I get a little space time to work on it :)

**Comment by GurliGebis** [comment]
I have just push version `10.2.5-20240225_1`, so within a few hours, you should be able to download it.

**Comment by nickdwaters** [comment]
Thank you for working on this. Some testing results for you ~

I went to Waking Shores and did a search for thunderfoot.  The
storm-touched still showed, which I had not collected.

In Thaldrassuz I had already collected the two ducklings, but not Annuna.
I turned on missing, and only Annuna showed, as expected. However, when I
did the name search for duckling, Annuna still showed.

**Comment by GurliGebis** [comment]
Did you change the filter type from Missing to Name Filter?
There doesn't seems to be a way to hide the text box depending on the dropdown values, so the way to do it is a bit confusing.

**Comment by nickdwaters** [comment]
Yes i set it to text filter, provided name, and clicked okay.

**Comment by GurliGebis** [comment]
I just tried following what you described, but the filtering seems to be working as expected for me.
Please attach a screenshot of your options dialog, and of your map.

**Comment by nickdwaters** [comment]
Hi,

With the following settings, note the name filter is set to "unborn":

[image: image.png]

Gives you the following screen, which includes the battlepet I have not yet
captured (oily slimeling), as well as the unborn. When using the name
filter, only the battlepets that contain the text should display,
regardless if missing or not.

[image: image.png]

Standard "missing" works perfect.

**Comment by GurliGebis** [comment]
It seems like images cannot be uploaded when replying by email.
Can you try and upload them to imgur, and then link to them instead?
