### ISSUE TITLE
Feature Request: Max Rare mode

### ISSUE THREAD

**Issue by davidmc24** [GurliGebis/WoWAddon-BattlePetCompletionist#17]
Thanks for the great plugin. For the pets that allow it, I try to collect 3 rare.  I've been wishing that there were two new options:

* a map icon mode for "max rare" rather than just max collected (UPDATE: see #18)
* the forfeit prompt to be based on lowest rarity rather than highest
* the forfeit prompt to treat less than max collected as uncollected

I'm happy to work on a PR in that sort of direction if you think this might make sense. Also open to other suggestions.

**Comment by GurliGebis** [comment]
Sounds like some good ideas 🙂
Pull requests are more than welcome, just remember to allow the current behaviour as well.
Thank you for helping 😃

**Comment by davidmc24** [comment]
> Just remember to allow the current behaviour as well

Of course!

**Comment by GurliGebis** [comment]
Thank you again for helping out 🙂
I have pushed `10.2.5-20240317_1` with your patches - it should be available within a few hours.

**Comment by davidmc24** [comment]
Thanks for the prompt merge. I'm still planning on working on a new forfeit setting, but that may take a bit longer.

**Comment by GurliGebis** [comment]
So, take your time 🙂
