### ISSUE TITLE
Addon Not Workikng

### ISSUE THREAD

**Issue by GGRivolf** [GurliGebis/WoWAddon-BattlePetCompletionist#21]
Hello, addon just doesn't work with any settings (filtring/missing/etc).

**Comment by GurliGebis** [comment]
Hey, if you set the filter to "All" - does it show any pets on the map? (Just to see if it is the filtering of something else)

**Comment by GGRivolf** [comment]
> Hey, if you set the filter to "All" - does it show any pets on the map? (Just to see if it is the filtering of something else)

I found a problem addon doesn't support russian localization. I just test it in english and this work fine. Look nice btw

**Comment by GurliGebis** [comment]
Okay, so the problem is when you run WoW with russian localization? (Or am I misunderstanding)

**Comment by GGRivolf** [comment]
Yes on the Russian localization addon does not work.

**Comment by GGRivolf** [comment]
> Okay, so the problem is when you run WoW with russian localization? (Or am I misunderstanding)

Yes on the Russian localization addon does not work.

**Comment by GurliGebis** [comment]
That's strange, since there shouldn't be anything in there causing it.
Can you try and install the `BugGrabber` and `BugSack` addons, and see if any errors is shown in there?

**Comment by GurliGebis** [comment]
Hmm, I'll have to implement debug logging (it's been on my todo list for a while).
It might take a little while before I get time to do it.

**Comment by GurliGebis** [comment]
@GGRivolf The latest version `10.2.6-20240501-1` has a lot of changes to how the configuration is working.
Can I get you to try it, and see if it works for you?

**Comment by GGRivolf** [comment]
> @GGRivolf The latest version `10.2.6-20240501-1` has a lot of changes to how the configuration is working. Can I get you to try it, and see if it works for you?

Test it and nothing change for me

**Comment by GurliGebis** [comment]
Hmm, okay, I'll see what I can do with regards to adding debug logging.

**Comment by GurliGebis** [comment]
@GGRivolf I have just pushed release `11.0.0-20240801-1` - can you please test if that solves the issue, and reopen the ticket if it is still an issue?
