### ISSUE TITLE
Data for Hissing Chitterspine

### ISSUE THREAD

**Issue by davidmc24** [GurliGebis/WoWAddon-BattlePetCompletionist#24]
This pet seems to be missing from the zone data for Nazjatar.  It's in a cave, which means using the actual map coordinates may be a bit weird, but an entry for the entrance to the cave might be useful (`/way Nazjatar 42.4, 13.2`).

Actual observed coords:

* Chitterspine Grotto 62.28, 51.66
* Chitterspine Grotto 49.01, 35.07

You can see the whole cave in pet tracking, so I probably wouldn't bother with more than that.

https://www.wowhead.com/npc=154708/hissing-chitterspine

**Comment by GurliGebis** [comment]
I do wonder why Wowhead doesn't have any data on the location of the pet.
It's been a while since I captued that pet - so please correct me if I'm wrong.
The pet has it's own cave, with it's own map? (Since all pet data is stored in pet->mapid->coordinates)

**Comment by davidmc24** [comment]
It's probably because it isn't on the overland map. The cave isn't just for this pet; there's another (more common) pet that also spawns in there, plus a bunch of mobs and a rare.

**Comment by davidmc24** [comment]
Next time I'm over there I'll snap a couple screenshots.

**Comment by davidmc24** [comment]
See attached
![Just outside of entrance to cave](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/447825/461ad77a-2daa-4f51-950c-b6347989099e)

![Just inside of entrance to cave](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/447825/c851a303-8309-4356-aba5-6a543bc8c679)

![Hover on the pet tracking](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/447825/2218a85c-6be2-4e03-a7a3-b60af4e74848)

A couple spawn locations I captured

* ![WoWScrnShot_042124_190844](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/447825/a3f42b23-5570-4c5b-932a-db5b827e25da)
* ![WoWScrnShot_042124_190938](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/447825/bda366a1-459f-4922-8d3f-1e018f72e632)

There is another spot or two a bit northwest, I think.

**Comment by davidmc24** [comment]
Want me to try my hand at an update to `Modules/Data/Source/PetData.json` for it?

**Comment by davidmc24** [comment]
If you are interested, https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/pull/25 looks pretty good to me.

**Comment by GurliGebis** [comment]
Thanks, I will take a look at it when I get home from work 🙂

**Comment by GurliGebis** [comment]
Today has been quiet busy, so it will have to wait until tomorrow :)

**Comment by davidmc24** [comment]
No rush

**Comment by GurliGebis** [comment]
I managed to get time to get it merged 🙂
