### ISSUE TITLE
Broker display and tooltip can get out-of-sync

### ISSUE THREAD

**Issue by davidmc24** [GurliGebis/WoWAddon-BattlePetCompletionist#26]
This seems particularly likely to occur if you're going in and out of small maps a lot (such as caves).

I'm planning on submitting a fix once I figure out what to do about it.  It's almost certainly an event that needs to trigger both updates that's currently only triggering one.

**Comment by GurliGebis** [comment]
I just took a look at it during my lunch break 😊
We are subscribing to the `ZONE_CHANGED_NEW_AREA` event, so it should be working.
How fast are you changing zone? (like, are you standing on the border and running back/forth?) - maybe there is a rate-limit on event publishing?
