### ISSUE TITLE
Data for Forbidden Reach world quest pets

### ISSUE THREAD

**Issue by davidmc24** [GurliGebis/WoWAddon-BattlePetCompletionist#28]
I'm working on a PR for this, but need to wait until all the world quests come up to make sure I get the coordinates right, since for some reason the ones listed on wowhead don't seem to be right any more.

https://www.wowhead.com/npc=200772/flow
https://www.wowhead.com/npc=200685/vortex
https://www.wowhead.com/npc=200693/tremblor
https://www.wowhead.com/npc=200689/wildfire

**Comment by GurliGebis** [comment]
Thank you :) I have pushed `10.2.6-20240428-1` with the changes
