### ISSUE TITLE
Request: See opponent's active abilities

### ISSUE THREAD

**Issue by MystbornGames** [GurliGebis/WoWAddon-BattlePetCompletionist#33]
Hi Gurli! Very much enjoying this addon and appreciate the work you've put in. One thing I do still miss from PetTracker is having opponent's abilities show up during a fight, like so:

https://media.forgecdn.net/attachments/667/529/enemy-bar-and-warnings.jpg

Any chance that could be added?

Thanks!

**Comment by davidmc24** [comment]
Gurli has another addon for that, https://www.curseforge.com/wow/addons/pokemon-trainer-ng

If that isn't to your liking, this one provides the ability to show opponent abilities in a more minimalistic manner: https://www.curseforge.com/wow/addons/battle-pet-battle-ui-tweaks

**Comment by GurliGebis** [comment]
Hey,

Yep, that is what I would recommend.
I like to keep it separate, to avoid too much overlap.
