### ISSUE TITLE
Right click on broker plug-in

### ISSUE THREAD

**Issue by Mike160770** [GurliGebis/WoWAddon-BattlePetCompletionist#47]
Hey - nice work!

One small "issue": When I right-click on the add-on icon in a data broker (e.g. bazooka), the "general settings" window of the game opens. Is it possible to implement the feature that on this right-click the options of the add-on show up?

Greetings from Austria

**Comment by davidmc24** [comment]
Should be possible.  It worked the way you wanted before the pre-patch API changes.  It looks like there's an argument in the new API, and AceConfig has support for it.  I'll take a look.

**Comment by davidmc24** [comment]
PR submitted.  Please take a look when you have a chance, @GurliGebis
