### ISSUE TITLE
Request: Add enemy pet moves display

### ISSUE THREAD

**Issue by SisterSkaoi** [GurliGebis/WoWAddon-BattlePetCompletionist#53]
As per title, one feature I'm really missing using this morally superior battle pet addon is that display above the pet combat bars that shows the active enemy pet moves & displays their cooldowns. Is this something that can be added?

**Comment by GurliGebis** [comment]
No worries 🙂 I'm just happy you like the addon so much that you take the time to suggest improvements 😀
