### ISSUE TITLE
The pet [Ravenous Shalewing] is not available, yet it is shown on the map of Isle of Dorn

### ISSUE THREAD

**Issue by VirgilRex** [GurliGebis/WoWAddon-BattlePetCompletionist#56]
The pet was datamined on the 10.1 PTR, but it has no known availability yet. Some critters can be found with the same name, but killing them wiill not make this pet spawn. It is not registered in the pet journal inside the game. Here is a list with all the pets that were datamined but are not listed in the game yet. [Link](https://www.warcraftpets.com/wow-pets/unlisted/)

Knowing all these, the pet should not appear on the map (in multiple points in the Isle of Dorn), yet it does.

**Comment by GurliGebis** [comment]
Thank you, I'll see if I can get time to fix my import script to allow for exclusions this weekend 🙂

**Comment by GurliGebis** [comment]
I have made a new release, with this pet excluded 🙂

**Comment by VirgilRex** [comment]
Thank you for the quick response

**Comment by VirgilRex** [comment]
@GurliGebis It is still appearing on 3 spots in the map.

**Comment by GurliGebis** [comment]
Can you attach a screenshot?

**Comment by VirgilRex** [comment]
Srry, I forgot about it. Here it is 
![Mapa Dornogal](https://github.com/user-attachments/assets/8d4c0ba9-5660-4fac-bdf3-3ff11646bf1e)
My game and interface are in spanish, srry about it, but you get the idea

**Comment by GurliGebis** [comment]
Thanks, I'll take a look at it 🙂

**Comment by GurliGebis** [comment]
Those are `Shalewing Devourer`, not `Ravenous Shalewing`
![billede](https://github.com/user-attachments/assets/cca39a1e-7162-41e9-a396-5eb80a4cefae)
