### ISSUE TITLE
Please add exclamation mark for wild pets which are not caught yet

### ISSUE THREAD

**Issue by sirzooro** [GurliGebis/WoWAddon-BattlePetCompletionist#7]
Hi,
PetTracker addon shows exclamation mark and small popup message when pet is not caught yet or is an upgrade of owned one(s) - see screen below. I miss this exclamation mark, it allowed me to quickly tell if any of missing pets are battling. Could you add it to your addon too? Thanks!

![image](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/1969912/b76685bd-3a55-4fdf-b9c2-dd92a48f6e93)

**Comment by GurliGebis** [comment]
I will see what I can do.
I cannot use the code from PetTracker, so I would have to do it from scratch 🙂

**Comment by GurliGebis** [comment]
I have implemented in a different way 🙂

![billede](https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist/assets/13592619/0c5c4c55-a99a-4bd9-bccb-ab5bc6267d07)

When you start a pet battle, where there is one or more pets that is unknown, this dialog shows for 5 seconds.
It only shows for uncollected pets, not for quality upgrade.

Version 10.1.7_20231002_1 that should be released shortly contains this.

**Comment by sirzooro** [comment]
Thanks!
