### ISSUE TITLE
dd support for Blizzard's "addon compartment" feature 

### ISSUE THREAD

**Issue by KatyPurry** [GurliGebis/WoWAddon-BattlePetCompletionist#9]
Hello,
Is it possible to add the [addon compartment](https://wowpedia.fandom.com/wiki/Addon_compartment) feature ?
Thank you

**Comment by GurliGebis** [comment]
It should be possible, I'll take a look at it.

**Comment by GurliGebis** [comment]
Yep, that was pretty easy to implement - release 10.1.7-20231011_1 has been pushed, it should show up within a few hours.
